jobs = [
    {"company": "amazon", "url": "https://www.amazon.jobs/en/search?offset=0&result_limit=10&sort=relevant&country%5B%5D=USA&state%5B%5D=Virginia&state%5B%5D=Maryland&state%5B%5D=District%20of%20Columbia&distanceType=Mi&radius=24km&latitude=&longitude=&loc_group_id=&loc_query=&base_query=&city=&country=&region=&county=&query_options=&"},
    {"company": "aecom", "url": "https://aecom.jobs/locations/virginia/jobs/"}, #https://aecom.jobs/locations/maryland/jobs/, https://aecom.jobs/locations/district-of-columbia/jobs/
    {"company": "jobs_capitalone", "url": "https://www.capitalonecareers.com/search-jobs"},
    {"company": "clarkconstruction", "url": "https://www.clarkconstruction.com/build-your-career/search-apply?page=1"},
    {"company": "exelon", "url": "https://jobs.exeloncorp.com/careers-home/jobs?state=Maryland%7CWashington,%20DC&page=1"},
    {"company": "george_washington_university", "url": "https://www.gwu.jobs/postings/search"},
    {"company": "georgetown_university", "url": "https://georgetown.wd1.myworkdayjobs.com/Georgetown_Admin_Careers"},
    {"company": "howard_university", "url": "https://howard.wd1.myworkdayjobs.com/HU"},
    {"company": "inova", "url": "https://elar.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?mode=location"},
    {"company": "jhons_hopkins", "url": "https://jobs.jhu.edu/search/?createNewAlert=false&q=&optionsFacetsDD_facility=&optionsFacetsDD_dept=&optionsFacetsDD_shifttype=&optionsFacetsDD_customfield1=&optionsFacetsDD_state="},
    {"company": "jp_morgan_chase", "url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?location=Washington%2C+DC%2C+United+States&locationId=300000020705795&locationLevel=city&mode=location&radius=25&radiusUnit=MI"},
    {"company": "maximus", "url": "https://maximus.avature.net/careers/SearchJobs/?6100=6047&6100_format=6846&6097=%5B11232%2C11245%2C11275%5D&6097_format=6843&listFilterMode=1&folderRecordsPerPage=6&"},
    {"company": "mcdean", "url": "https://careers.mcdean.com/jobs?page=1&locations=Aldie%C2%A0,Virginia,United%20States%7CAlexandria%C2%A0,Virginia,United%20States%7CAnnapolis%20Junction%C2%A0,Maryland,United%20States%7CAnnapolis,Maryland,United%20States%7CArlington%C2%A0,Virginia,United%20States%7CAshburn%C2%A0,Virginia,United%20States%7CBaltimore%C2%A0,Maryland,United%20States%7CBethesda%C2%A0,Maryland,United%20States%7CBoydton%C2%A0,Virginia,United%20States%7CCaroline%20County%C2%A0,Virginia,United%20States%7CChantilly%C2%A0,Virginia,United%20States%7CCharlottesville%C2%A0,Virginia,United%20States%7CChesapeake%C2%A0,Virginia,United%20States%7CChristiansburg%C2%A0,Virginia,United%20States%7CCollege%20Park%C2%A0,Maryland,United%20States%7CDistrict%20of%20Columbia,Washington~%20DC,United%20States%7CDulles%C2%A0,Virginia,United%20States%7CFairfax%C2%A0,Virginia,United%20States%7CFalls%20Church%C2%A0,Virginia,United%20States%7CFort%20Meade%C2%A0,Maryland,United%20States%7CFredericksburg%C2%A0,Virginia,United%20States%7CFrederick%C2%A0,Maryland,United%20States%7CFt.%20Belvoir,Virginia,United%20States%7CGaithersburg%C2%A0,Maryland,United%20States%7CHarrisonburg%C2%A0,Virginia,United%20States%7CLaurel%C2%A0,Maryland,United%20States%7CLeesburg%C2%A0,Virginia,United%20States%7CLottsburg%C2%A0,Virginia,United%20States%7CManassas%C2%A0,Virginia,United%20States%7CMcLean%C2%A0,Virginia,United%20States%7CNorfolk%C2%A0,Virginia,United%20States%7CRichmond%C2%A0,Virginia,United%20States%7CSouth%20Hill%C2%A0,Virginia,United%20States%7CSpringfield%C2%A0,Virginia,United%20States%7CSterling%C2%A0,Virginia,United%20States%7CTysons%C2%A0,Virginia,United%20States%7CUrbana%C2%A0,Maryland,United%20States%7CVirginia%20Beach%C2%A0,Virginia,United%20States%7CWarrenton%C2%A0,Virginia,United%20States%7CWashington%C2%A0,Washington~%20DC,United%20States%7CWinchester%C2%A0,Virginia,United%20States"},
    {"company": "medstarhealth", "url": "https://careers.medstarhealth.org/global/en/search-results"},
    {"company": "northrop_grumman", "url": "https://jobs.northropgrumman.com/careers?pid=1340058149304&State=Maryland&triggerGoButton=false&triggerGoButton=true&source=APPLICANT_SOURCE-3-504"},
    {"company": "truist", "url": "https://careers.truist.com/us/en/search-results?keywords="},
    {"company": "underarmour", "url": "https://careers.underarmour.com/search/?searchby=location&createNewAlert=false&q=&locationsearch=Maryland&geolocation="},
] 